# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
env:
   - PYTHON=""
after_success:
  # push coverage results to Codecov
- julia -e 'using Pkg;
            Pkg.add("Coverage");
            using Coverage;
            Codecov.submit(Codecov.process_folder())'
